<?php
/* Novatorix Admin Panel Options*/
$themename = "Novatorix";
$shortname = "nvx";
$version = "1.4";

/* Get CSS files into a array list */
$theme_styles = array();
if(is_dir(TEMPLATEPATH . "/css/")) {
	if($open_dirs = opendir(TEMPLATEPATH . "/css/")) {
	while(($file_name = readdir($open_dirs)) !== false) {
	if(stristr($file_name, ".css") !== false) {
		$theme_styles[] = $file_name;
	}}}
}

/* Put theme pages into array */
$theme_pages = get_pages();
$pages_array = array();
foreach($theme_pages as $apage) 
{
	$pages_array[$page->ID] = $page->post_title;
}

/* Piecemaker Tween Types */
$tween_types = array("linear", "easeInSine", "easeOutSine", "easeInOutSine", "easeInCubic", "easeOutCubic", "easeInOutCubic", "easeOutInCubic", "easeInQuint", "easeOutQuint", "easeInOutQuint", "easeOutInQuint", "easeInCirc", "easeOutCirc", "easeInOutCirc", "easeOutInCirc", "easeInBack", "easeOutBack", "easeInOutBack", "easeOutInBack", "easeInQuad", "easeOutQuad", "easeInOutQuad", "easeOutInQuad", "easeInQuart", "easeOutQuart", "easeInOutQuart", "easeOutInQuart", "easeInExpo", "easeOutExpo", "easeInOutExpo", "easeOutInExpo", "easeInElastic", "easeOutElastic", "easeInOutElastic", "easeOutInElastic", "easeInBounce", "easeOutBounce", "easeInOutBounce", "easeOutInBounce", "easeInOutBack");

/* Theme options */
$options = array (
		
	/* General options*/
	array( "type" => "headline",
			"name" => "General"),			
	array( "type" => "open"),
	array(	"name" => "Color Scheme",
			"desc" => "Please select your preferred color scheme.",
			"id" => $shortname."_style",
			"type" => "select",
			"std" => "style.css",
			"options" => $theme_styles),
	array(	"name" => "Logo",
			"desc" => "Please enter an URL or upload your custom logo.",
            "id" => $shortname."_logo",
            "type" => "text"),	
	array(	"name" => "Home page slogan",
			"desc" => "Please enter your header slogan (or select widget).",
            "id" => $shortname."_slogan",
            "type" => "text"),					
	array(  "name" => "Blog Page",
			"desc" => "Select page that will show Blog posts.",
            "id" => $shortname."_blog_page",
            "type" => "blog_page"),	
	array(	"name" => "Enable default menu",
			"desc" => "Enable classic wordpress menu that are created from pages.",
			"type" => "checkbox",		
			"id" => $shortname."_wp_3_0_menus"),						
	array(	"name" => "Exclude Pages",
			"id" => $shortname."_exclude_pages",
			"std" => "",
			"desc" => "Exclude pages from header menu. Works only when Default Menu is checked.",
            "type" => "exclude_pages",
			"options" => $pages_array),
	array(	"name" => "Exclude Blog Categories",
			"id" => $shortname."_exclude_categories",
			"std" => "",
			"desc" => "Exclude categories from Blog. Selected Categories will not be show in Blog categories and in Blog posts.",
            "type" => "exclude_categories",
			"options" => $cats_menu),
	
	array(	"name" => "Enable breadcrumbs",
			"type" => "checkbox",		
			"id" => $shortname."_breadcrumbs"),			
			
	array(	"name" => "Enable 'About the Author section'",
			"desc" => "Enable 'About the Author' section in posts.",
			"type" => "checkbox",		
			"id" => $shortname."_about_the_author_posts"),						

	array(	"name" => "Enable 'Enjoyed this Post' and 'Related Posts' sections<br><br>",
			"desc" => "Enable 'Enjoyed this Post' and 'Related Posts' sections in posts.",
			"type" => "checkbox",		
			"id" => $shortname."_enjoyed_related_posts"),						
									
			
	array(	"name" => "Tracking Code",
			"desc" => "Insert your tracking code here (e.g. Google Analytics).<br>The code will be added to the footer of each pages.",
			"id" => $shortname."_tracking_code",
			"type" => "textarea"),
	array(    "type" => "close"),

	
	
	
	/* Home page options*/
	array( "type" => "headline",
			"name" => "Homepage 3 Columns"),			
	array( "type" => "open"),
	array(	"name" => "First column title",
			"desc" => "Please enter title for first column.",
            "id" => $shortname."_1column_title",
            "type" => "text"),
	array(	"name" => "First url link",
			"desc" => "Please enter url link for first column.",
            "id" => $shortname."_1column_url_link",
            "type" => "text"),
	array(	"name" => "First image url",
			"desc" => "Please enter image full url for first column (max image width 280px).",
            "id" => $shortname."_1column_imageurl",
            "type" => "text"),			
	array(	"name" => "First column text",
			"desc" => "Please enter your first column text e.g. short description of your company, service or product.",
			"id" => $shortname."_1column_text",
			"type" => "textarea"),
	array(	"type" => "solidline"),

	array(	"name" => "Second column title",
			"desc" => "Please enter title for Second column (or select widget).",
            "id" => $shortname."_2column_title",
            "type" => "text"),
	array(	"name" => "Second url link",
			"desc" => "Please enter url link for Second column.",
            "id" => $shortname."_2column_url_link",
            "type" => "text"),
	array(	"name" => "Second image url",
			"desc" => "Please enter image full url for second column (max image width 280px).",
            "id" => $shortname."_2column_imageurl",
            "type" => "text"),					
	array(	"name" => "Second column text",
			"desc" => "Please enter your Second column text e.g. short description of your company, service or product.",
			"id" => $shortname."_2column_text",
			"type" => "textarea"),
	array(	"type" => "solidline"),
	
	array(	"name" => "Third column title",
			"desc" => "Please enter title for Third column (or select widget).",
            "id" => $shortname."_3column_title",
            "type" => "text"),		
	array(	"name" => "Third url link",
			"desc" => "Please enter url link for Third column.",
            "id" => $shortname."_3column_url_link",
            "type" => "text"),			
	array(	"name" => "Third image url",
			"desc" => "Please enter image full url for third column (max image width 280px).",
            "id" => $shortname."_3column_imageurl",
            "type" => "text"),					
	array(	"name" => "Third column text",
			"desc" => "Please enter your Third column text e.g. short description of your company, service or product.",
			"id" => $shortname."_3column_text",
			"type" => "textarea"),
	array(	"type" => "solidline"),
	
	array(    "type" => "close"),	
	
	
	
	/* Home page options*/
	array( "type" => "headline",
			"name" => "Homepage 4 Columns"),			
	array( "type" => "open"),
	array(	"name" => "First column title",
			"desc" => "Please enter title for first column.",
            "id" => $shortname."_4cols_1column_title",
            "type" => "text"),				
	array(	"name" => "First column text",
			"desc" => "Please enter your first column text e.g. short description of your company, service or product.",
			"id" => $shortname."_4cols_1column_text",
			"type" => "textarea"),
	array(	"type" => "solidline"),
	
	array(	"name" => "Second column title",
			"desc" => "Please enter title for Second column.",
            "id" => $shortname."_4cols_2column_title",
            "type" => "text"),					
	array(	"name" => "Second column text",
			"desc" => "Please enter your Second column text e.g. short description of your company, service or product.",
			"id" => $shortname."_4cols_2column_text",
			"type" => "textarea"),
	array(	"type" => "solidline"),
	
	array(	"name" => "Third column title",
			"desc" => "Please enter title for Third column.",
            "id" => $shortname."_4cols_3column_title",
            "type" => "text"),					
	array(	"name" => "Third column text",
			"desc" => "Please enter your Third column text e.g. short description of your company, service or product.",
			"id" => $shortname."_4cols_3column_text",
			"type" => "textarea"),
	array(	"type" => "solidline"),
	
	array(	"name" => "Fourth column title",
			"desc" => "Please enter title for Fourth column.",
            "id" => $shortname."_4cols_4column_title",
            "type" => "text"),			
	array(	"name" => "Fourth column text",
			"desc" => "Please enter your Fourth column text e.g. short description of your company, service or product.",
			"id" => $shortname."_4cols_4column_text",
			"type" => "textarea"),		
	array(	"type" => "solidline"),
	
	array(    "type" => "close"),		
	
		/* Piecemaker Options */
	array( "type" => "headline",
			"name" => "Homepage slider"),			
	array( "type" => "open"),		
	
	array(  "name" => "Images count",
			"desc" => "Please enter how many images to show in homepage slider. Note: click 'Save changes' and after insert info.",
			"id" => $shortname."_slider_images_count",
			"type" => "numbers",
			"std" => "0"),	
			
	array(	"name" => "Select slider",
			"desc1" => "Nivo slider",
			"desc2" => "Piecemaker 3D slider",
			"desc3" => "Use static image",
			
			"value1" => "nivo",
			"value2" => "piecemaker",
			"value3" => "staticimage",
			
			"id" => $shortname."_slider_switch",
			"type" => "radio_sliders",
			'selector' => true),
				

	array(  "name" => "Static Image URL",
			"desc" => "Enter full image url if you have selected <strong>Use static image</strong>.",
			"id" => $shortname."_staticimage_url",
			"type" => "text"),
			
	array(  "name" => "Static Go To URL",
			"desc" => "Enter url to click on image (optional) if you have selected <strong>Use static image</strong>.",
			"id" => $shortname."_staticimage_gotourl",
			"type" => "text"),	
			
	array(  "name" => "Images count",
			"desc" => "Please enter how many images to show in homepage slider. ",
			"id" => $shortname."_piecemaker_text",
			"type" => "piecemaker_text",
			"std" => "5"),	
	array(  "name" => "Image Width",
			"desc" => "The width of the images to be loaded.",
			"id" => $shortname."_imageWidth",
			"type" => "text",
			"std" => "900"),
	array(  "name" => "Image Height",
			"desc" => "The height of the images to be loaded.",
			"id" => $shortname."_imageHeight",
			"type" => "text",
			"std" => "400"),			
	array(  "name" => "Segments",
			"desc" => "Number of segments in which the image will be sliced.",
			"id" => $shortname."_segments",
			"type" => "text",
			"std" => "7"),		
	array(  "name" => "Tween Time",
			"desc" => "Number of seconds for each element to be turned.",
			"id" => $shortname."_tweenTime",
			"type" => "text",
			"std" => "1.2"),
	array(  "name" => "Tween Delay",
			"desc" => "Number of seconds from one element starting to turn to the next element starting.",
			"id" => $shortname."_tweenDelay",
			"type" => "text",
			"std" => "0.1"),
	array( "name" => "Tween Type",
			"desc" => "Type of transition from Caurina's Tweener class.",
			"id" => $shortname."_tweenType",
			"type" => "select_tweenType",
			"options" => $tween_types,
			"std" => "Choose Tween Type"),
	array(  "name" => "Z Distance",
			"desc" => "To which extend are the cubes moved on z axis when being tweened. Negative values bring the cube closer to the camera, positive values take it further away. A good range is roughly between -200 and 700.",
			"id" => $shortname."_zDistance",
			"type" => "text",
			"std" => "0"),
	array(  "name" => "Expand",
			"desc" => "To which extend are the cubes moved away from each other when tweening.",
			"id" => $shortname."_expand",
			"type" => "text",
			"std" => "20"),
	array(  "name" => "Inner Color",
			"desc" => "Color of the sides of the elements in hex values (e.g. 0x000000 for black).",
			"id" => $shortname."_innerColor",
			"type" => "text",
			"std" => "0x111111"),
	array(  "name" => "Text Background Color",
			"desc" => "Color of the description text background in hex values (e.g. 0xFF0000 for red).",
			"id" => $shortname."_textBackground",
			"type" => "text",
			"std" => "0x0064C8"),
	array(  "name" => "Shadow Darkness",
			"desc" => "To which extend are the sides shadowed, when the elements are tweening and the sided move towards the background. 100 is black, 0 is no darkening.",
			"id" => $shortname."_shadowDarkness",
			"type" => "text",
			"std" => "100"),
	array(  "name" => "Text Distance",
			"desc" => "Distance of the info text to the borders of its background.",
			"id" => $shortname."_textDistance",
			"type" => "text",
			"std" => "25"),
	array(  "name" => "Auto Play",
			"desc" => "Number of seconds to the next image when autoplay is on. Set 0, if you don't want autoplay.",
			"id" => $shortname."_autoplay",
			"type" => "text",
			"std" => "10"),
	array(	"type" => "close"),
	
		/* Portfolio options*/
	array( "type" => "headline",
			"name" => "Portfolio"),			
	array( "type" => "open"),
	array(	"name" => "Portfolio Gallery view items",
			"desc" => "Please choose the number of items you want to display on your Portfolio Gallery view Pages.",
            "id" => $shortname."_portfolio_items",
            "type" => "numbers",
			"std" => "12"),		
	array(	"type" => "solidline"),	
	array(	"name" => "Assign Portfolio Page to a Category",
			"desc" => "Select a Page to display Portfolio Category",
			"id" => $shortname."_portfolio_add",
			"type" => "portfolio_add"),		
	array(	"type" => "solidline"),		
	array(  "type" => "close"),		
		
		

	
	/* Get in Touch Footer options*/
	array( "type" => "headline",
			"name" => "Get in touch"),			
	array( "type" => "open"),	
	array(	"name" => "Enable RSS",
			"type" => "checkbox",		
			"id" => $shortname."_display_rss"),
	array(	"name" => "RSS",
			"desc" => "Please enter RSS url.",
            "id" => $shortname."_rss",
            "type" => "text"),		
	array(	"type" => "solidline"),			
	array(	"name" => "Enable Twitter",
			"type" => "checkbox",		
			"id" => $shortname."_display_twitter"),	
	array(	"name" => "Twitter",
			"desc" => "Please enter Twitter url.",
            "id" => $shortname."_twitter",
            "type" => "text"),	
	array(	"type" => "solidline"),						
	array(	"name" => "Enable Facebook",
			"type" => "checkbox",		
			"id" => $shortname."_display_facebook"),			
	array(	"name" => "Facebook",
			"desc" => "Please enter Facebook url.",
            "id" => $shortname."_facebook",
            "type" => "text"),	
	array(	"type" => "solidline"),						
	array(	"name" => "Enable LinkedIn",
			"type" => "checkbox",		
			"id" => $shortname."_display_linkedin"),			
	array(	"name" => "LinkedIn",
			"desc" => "Please enter LinkedIn url.",
            "id" => $shortname."_linkedin",
            "type" => "text"),
	array(    "type" => "close"),
	
	
		/* Testimonials Footer options*/
	array( "type" => "headline",
			"name" => "Footer"),			
	array( "type" => "open"),
	array(	"name" => "First testimonial headline",
			"desc" => "Please enter first testimonial headline.",
            "id" => $shortname."_first_testimonial_headline",
            "type" => "text"),
	array(	"name" => "First testimonial",
			"desc" => "Please enter first testimonial.",
            "id" => $shortname."_first_testimonial",
            "type" => "textarea"),		
	array(	"name" => "Second testimonial headline",
			"desc" => "Please enter second testimonial headline.",
            "id" => $shortname."_second_testimonial_headline",
            "type" => "text"),
	array(	"name" => "Second testimonial",
			"desc" => "Please enter second testimonial (or select widget).",
            "id" => $shortname."_second_testimonial",
            "type" => "textarea"),	
	array(	"name" => "Address",
			"desc" => "Please enter your address (or select widget).",
            "id" => $shortname."_adress",
            "type" => "text"),	
	array(	"name" => "Phone",
			"desc" => "Please enter your phone number (or select widget).",
            "id" => $shortname."_phone",
            "type" => "text"),			
	array(	"name" => "Your fax",
			"desc" => "Please enter your fax number (or select widget).",
            "id" => $shortname."_fax",
            "type" => "text"),				
	array(	"name" => "Your email",
			"desc" => "Please enter email address (or select widget).",
            "id" => $shortname."_email",
            "type" => "text"),			
	array(	"name" => "Footer",
			"desc" => "Copyrigh text content. Alowed html tags (or select widget).",
			"id" => $shortname."_footer",
			"type" => "textarea",
			"std" => '&copy; Copyright 2010. All Rights Reserved (or select widget).'),			
	array(    "type" => "close")
	
);
?>